kind: Deployment
apiVersion: apps/v1
metadata:
  name: wordpress-2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wordpress
      tier: frontend
      test: external-db
  template:
    metadata:
      labels:
        app: wordpress
        tier: frontend
        test: external-db
    spec:
      containers:
        - name: wordpress
          image: wordpress:4.9.8-apache
          volumeMounts:
            - name: ceph-nfs
              mountPath: /var/www/html/
          env:
            - name: WORDPRESS_DB_HOST
              value: mysql-external-db
            - name: WORDPRESS_DB_USER
              value: admin
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wp-mysql-external-password
                  key: mysql_user_password
          ports:
            - containerPort: 80
              name: wordpress
      volumes:
        - name: ceph-nfs
          persistentVolumeClaim:
            claimName: wp-pvc-2
---
kind: Service
apiVersion: v1
metadata:
  name: wordpress-2
  labels:
    app: wordpress
    tier: frontend
    test: external-db
spec:
  ports:
    - port: 80
  selector:
    app: wordpress
    tier: frontend
    test: external-db
  type: NodePort
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: wp-pvc-2
spec:
  storageClassName: cephfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi


