kind: Deployment
apiVersion: apps/v1
metadata:
  name: wordpress
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wordpress
      tier: frontend
  template:
    metadata:
      labels:
        app: wordpress
        tier: frontend
    spec:
      containers:
        - name: wordpress
          image: wordpress:4.9.8-apache
          volumeMounts:
            - name: ceph-nfs
              mountPath: /var/www/html/
          env:
            - name: WORDPRESS_DB_HOST
              value: mysql
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wp-mysql-password
                  key: mysql_root_password
          ports:
            - containerPort: 80
              name: wordpress
      volumes:
        - name: ceph-nfs
          persistentVolumeClaim:
            claimName: wp-pvc
---
kind: Service
apiVersion: v1
metadata:
  name: wordpress
  labels:
    app: wordpress
    tier: frontend
spec:
  ports:
    - port: 80
  selector:
    app: wordpress
    tier: frontend
  type: NodePort
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: wp-pvc
spec:
  storageClassName: cephfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi


